{
 "title": "AWS API Gateway & ALB Metrics",
 "description": "Merged dashboard for AWS API Gateway and Application Load Balancer metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "agg",
    "label": "Aggregation",
    "query": "1s,5s,10s,30s,1m,5m,15m,1h,6h,1d,7d,30d"
   },
   { "name": "region", "label": "Region", "query": "us-gov-east-1,us-gov-west-1" },
   {
    "name": "apiname",
    "label": "ApiName",
    "query": "dimension_values($region,AWS/ApiGateway,Count,ApiName)"
   },
   {
    "name": "stage",
    "label": "Stage",
    "query": "dimension_values($region,AWS/ApiGateway,Count,Stage, {\"ApiName\": \"$apiname\"})"
   },
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "us-gov-east-1,us-gov-west-1" },
   {
    "name": "loadbalancername",
    "label": "LoadBalancerName",
    "query": "dimension_values($region,AWS/ApplicationELB,ActiveConnectionCount,LoadBalancer)"
   }
  ]
 },
 "panels": [
  {
   "title": "AWS API Gateway Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "panels": [
    { "type": "query" },
    { "type": "query" },
    {
     "title": "Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${PROP('MetricName')} ${PROP('Stat')}",
       "metricName": "Count",
       "namespace": "AWS/ApiGateway",
       "options": {
        "showDisabledItems": false
       },
       "period": "$agg",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Latency / IntegrationLatency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${PROP('MetricName')} ${PROP('Stat')}",
       "metricName": "Latency",
       "namespace": "AWS/ApiGateway",
       "options": {
        "showDisabledItems": false
       },
       "period": "$agg",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${PROP('MetricName')} ${PROP('Stat')}",
       "metricName": "IntegrationLatency",
       "namespace": "AWS/ApiGateway",
       "options": {
        "showDisabledItems": false
       },
       "period": "$agg",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${PROP('MetricName')} ${PROP('Stat')}",
       "metricName": "Latency",
       "namespace": "AWS/ApiGateway",
       "options": {
        "showDisabledItems": false
       },
       "period": "$agg",
       "region": "$region",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "4XXError / 5XXError",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "id": "e400",
       "item": { "filter": "" },
       "label": "${PROP('MetricName')} ${PROP('Stat')}",
       "metricName": "4XXError",
       "namespace": "AWS/ApiGateway",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "id": "e500",
       "item": { "filter": "" },
       "label": "${PROP('MetricName')} ${PROP('Stat')}",
       "metricName": "5XXError",
       "namespace": "AWS/ApiGateway",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "alias": "Total Error Rate",
       "application": { "filter": "" },
       "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
       "expression": "SUM([e400,e500])*100/countt",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "id": "rate",
       "item": { "filter": "" },
       "label": "Total Error Rate",
       "metricEditorMode": 1,
       "metricName": "Count",
       "namespace": "AWS/ApiGateway",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "CacheHitCount / CacheMissCount",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${PROP('MetricName')} ${PROP('Stat')}",
       "metricName": "CacheHitCount",
       "namespace": "AWS/ApiGateway",
       "options": {
        "showDisabledItems": false
       },
       "period": "$agg",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "alias": "{{metric}} {{stat}}",
       "application": { "filter": "" },
       "dimensions": { "ApiName": "$apiname", "Stage": "$stage" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${PROP('MetricName')} ${PROP('Stat')}",
       "metricName": "CacheMissCount",
       "namespace": "AWS/ApiGateway",
       "options": {
        "showDisabledItems": false
       },
       "period": "$agg",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Documentation",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 29 },
     "options": {
      "content": "<a target=\"_blank\" href=\"http://www.monitoringartist.com\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-metrics-and-dimensions.html\">AWS CloudWatch API Gateway documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/1516\">Installed from Grafana.com dashboards</a>"
     }
    }
   ]
  },
  {
   "title": "AWS ALB Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "panels": [
    { "type": "query" },
    {
     "title": "RequestCount/TargetResponseTime",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "RequestCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "TargetResponseTime",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "HTTPCode_Target",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HTTPCode_Target_5XX_Count",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HTTPCode_Target_4XX_Count",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HTTPCode_Target_3XX_Count",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HTTPCode_Target_2XX_Count",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "HTTPCode_ELB",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HTTPCode_ELB_3XX_Count",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HTTPCode_ELB_4XX_Count",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HTTPCode_ELB_5XX_Count",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "ConnectionCount",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ActiveConnectionCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "NewConnectionCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "RejectedConnectionCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "TargetConnectionErrorCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "ConsumedLBCapacityUnits/ConsumedLCUs/ProcessedBytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ConsumedLBCapacityUnits",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ProcessedBytes",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ConsumedLCUs",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "TLSNegotiationErrorCount",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "TargetTLSNegotiationErrorCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ClientTLSNegotiationErrorCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "IPv6",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "IPv6RequestCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "IPv6ProcessedBytes",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "RuleEvaluations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "RuleEvaluations",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Auth",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ELBAuthError",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ELBAuthFailure",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ELBAuthSuccess",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ELBAuthRefreshTokenSuccess",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ELBAuthUserClaimsSizeExceeded",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ELBAuthLatency",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Documentation",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 81 },
     "options": {
      "content": "<a target=\"_blank\" href=\"http://www.monitoringartist.com\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html\">AWS CloudWatch ELB documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/650\">Installed from Grafana.com dashboards</a>"
     }
    }
   ]
  }
 ]
}